add_executable(snowy_core_tests core_tests.cpp)
target_link_libraries(snowy_core_tests PRIVATE snowy::snowy)
if(MSVC)
    target_compile_options(snowy_core_tests PRIVATE /W4 /WX /permissive-)
else()
    target_compile_options(snowy_core_tests PRIVATE -Wall -Wextra -Wpedantic -Werror)
endif()

add_test(NAME snowy.core COMMAND snowy_core_tests)
set_tests_properties(snowy.core PROPERTIES TIMEOUT 30)
add_executable(snowy_loop_tests loop_tests.cpp)
target_link_libraries(snowy_loop_tests PRIVATE snowy::snowy)
add_test(NAME snowy.loop COMMAND snowy_loop_tests)
set_tests_properties(snowy.loop PROPERTIES TIMEOUT 30)
add_executable(snowy_socket_tests socket_tests.cpp)
target_link_libraries(snowy_socket_tests PRIVATE snowy::snowy)
add_test(NAME snowy.socket COMMAND snowy_socket_tests)
set_tests_properties(snowy.socket PROPERTIES TIMEOUT 30)
add_executable(snowy_channel_tests channel_tests.cpp)
target_link_libraries(snowy_channel_tests PRIVATE snowy::snowy)
add_test(NAME snowy.channel COMMAND snowy_channel_tests)
set_tests_properties(snowy.channel PROPERTIES TIMEOUT 30)
add_executable(snowy_pool_tests pool_tests.cpp)
target_link_libraries(snowy_pool_tests PRIVATE snowy::snowy)
add_test(NAME snowy.pool COMMAND snowy_pool_tests)
set_tests_properties(snowy.pool PROPERTIES TIMEOUT 30)
