add_executable(snowy_runtime runtime.cpp)
target_link_libraries(snowy_runtime PRIVATE snowy::snowy)
add_executable(snowy_tcp tcp.cpp)
target_link_libraries(snowy_tcp PRIVATE snowy::snowy)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_executable(snowy_uring uring.cpp)
    target_include_directories(snowy_uring SYSTEM PRIVATE ${URING_INCLUDE_DIR})
    target_link_libraries(snowy_uring PRIVATE snowy::snowy ${URING_LIBRARY})
endif()
if(SNOWY_BUILD_TESTS)
    foreach(mode task schedule spawn)
        add_test(NAME bench_${mode} COMMAND snowy_runtime ${mode} 1000)
        set_tests_properties(bench_${mode} PROPERTIES TIMEOUT 30)
    endforeach()
    add_test(NAME bench_tcp COMMAND snowy_tcp 100 128)
    set_tests_properties(bench_tcp PROPERTIES TIMEOUT 30)
    if(TARGET snowy_uring)
        add_test(NAME bench_uring COMMAND snowy_uring 100 32)
        set_tests_properties(bench_uring PROPERTIES TIMEOUT 30)
    endif()
endif()
