foreach(example timer echo pipeline datagram read)
    add_executable(snowy_${example} ${example}.cpp)
    target_link_libraries(snowy_${example} PRIVATE snowy::snowy)
    if(SNOWY_BUILD_TESTS)
        if(example STREQUAL "read")
            add_test(NAME example_read COMMAND snowy_read ${PROJECT_SOURCE_DIR}/README.md)
        else()
            add_test(NAME example_${example} COMMAND snowy_${example})
        endif()
        set_tests_properties(example_${example} PROPERTIES TIMEOUT 10)
    endif()
endforeach()
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_executable(snowy_fixed fixed.cpp)
    target_link_libraries(snowy_fixed PRIVATE snowy::snowy)
    if(SNOWY_BUILD_TESTS)
        add_test(NAME example_fixed COMMAND snowy_fixed ${PROJECT_SOURCE_DIR}/README.md)
        set_tests_properties(example_fixed PROPERTIES TIMEOUT 10)
    endif()
endif()
